Update KDE runtime to 6.10
Need to import patch to fix libplacebo build failure:

===
Traceback (most recent call last):
  File "/run/build/libplacebo/_flatpak_build/../src/vulkan/utils_gen.py", line 205, in <module>
    registry = VkXML(ET.parse(xmlfile))
  File "/run/build/libplacebo/_flatpak_build/../src/vulkan/utils_gen.py", line 50, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/xml/etree/ElementTree.py", line 527, in __init__
    raise TypeError('expected an Element, not %s' %
                    type(element).__name__)
TypeError: expected an Element, not ElementTree
===

Patch: https://github.com/haasn/libplacebo/commit/12509c0f1ee8c22ae163017f0a5e7b8a9d983a17